// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGSPU5brpTYUqfGPQXtCEuQg3FCyMOLyA',
    appId: '1:772457775596:web:14567ff43c5bb1ac6140c9',
    messagingSenderId: '772457775596',
    projectId: 'medtag-825eb',
    authDomain: 'medtag-825eb.firebaseapp.com',
    storageBucket: 'medtag-825eb.appspot.com',
    measurementId: 'G-27E5PCQ3P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7cNlpSg_n4k197CAkgKaJf5Bov7jQgLU',
    appId: '1:772457775596:android:24beb852f6864e066140c9',
    messagingSenderId: '772457775596',
    projectId: 'medtag-825eb',
    storageBucket: 'medtag-825eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01A1rkh0dnOf6OskAFMVKZok29s8sP5o',
    appId: '1:772457775596:ios:85dab8c27e684ada6140c9',
    messagingSenderId: '772457775596',
    projectId: 'medtag-825eb',
    storageBucket: 'medtag-825eb.appspot.com',
    iosBundleId: 'com.example.medtagapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC01A1rkh0dnOf6OskAFMVKZok29s8sP5o',
    appId: '1:772457775596:ios:85dab8c27e684ada6140c9',
    messagingSenderId: '772457775596',
    projectId: 'medtag-825eb',
    storageBucket: 'medtag-825eb.appspot.com',
    iosBundleId: 'com.example.medtagapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGSPU5brpTYUqfGPQXtCEuQg3FCyMOLyA',
    appId: '1:772457775596:web:e2275e81d809f3ff6140c9',
    messagingSenderId: '772457775596',
    projectId: 'medtag-825eb',
    authDomain: 'medtag-825eb.firebaseapp.com',
    storageBucket: 'medtag-825eb.appspot.com',
    measurementId: 'G-JPHBJ188LM',
  );
}
